apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ollama
  ports:
    - port: {{ .Values.ollama.port }}
      targetPort: {{ .Values.ollama.port }}