apiVersion: v1
kind: Service
metadata:
  name: openwebui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: openwebui
  ports:
    - port: {{ .Values.openwebui.port }}
      targetPort: {{ .Values.openwebui.port }}
  type: NodePort